# Generated by Django 4.2 on 2023-04-14 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Groups_Users',
        ),
    ]
