# Generated by Django 4.2 on 2023-04-18 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_delete_groups_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_alter_leaders_leader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuserprofile',
            name='groups',
            field=models.ManyToManyField(related_name='users', to='groups.group'),
        ),
        migrations.AlterField(
            model_name='leaders',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.group'),
        ),
        migrations.AlterField(
            model_name='leaders',
            name='leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='leaders',
            unique_together={('group', 'leader')},
        ),
    ]
