# Generated by Django 4.2 on 2023-04-14 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_delete_groups_users'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuserprofile',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='users', to='groups.group'),
        ),
        migrations.CreateModel(
            name='Leaders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='groups.group')),
                ('leader', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.appuserprofile')),
            ],
            options={
                'db_table': 'leaders',
            },
        ),
    ]
