# Generated by Django 4.2 on 2023-04-17 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_appuserprofile_groups_leaders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaders',
            name='leader',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
