# Generated by Django 4.2 on 2023-04-19 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0002_delete_groups_users'),
        ('users', '0004_alter_appuserprofile_groups_alter_leaders_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_leader', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='groups.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'groups_users',
                'unique_together': {('group', 'user')},
            },
        ),
        migrations.RemoveField(
            model_name='appuserprofile',
            name='groups',
        ),
        migrations.DeleteModel(
            name='Leaders',
        ),
    ]
