# Generated by Django 4.2 on 2023-06-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_groupuser_last_operation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuserprofile',
            name='onboard',
            field=models.CharField(default='none', max_length=20),
        ),
    ]
