# Generated by Django 4.2 on 2023-04-11 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_sum', models.FloatField()),
                ('acc_currency', models.CharField(max_length=10)),
                ('acc_comment', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
        migrations.CreateModel(
            name='OperationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='OperationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_name', models.CharField(max_length=40)),
                ('temp_variant', models.CharField(max_length=10)),
                ('temp_recipient', models.CharField(max_length=100)),
                ('temp_sum', models.FloatField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.operationcategory')),
            ],
            options={
                'db_table': 'templates',
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op_variant', models.CharField(max_length=10)),
                ('op_date', models.DateTimeField()),
                ('op_recipient', models.CharField(max_length=100)),
                ('op_sum', models.FloatField()),
                ('op_comment', models.TextField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.account')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.operationcategory')),
            ],
            options={
                'db_table': 'operations',
            },
        ),
        migrations.CreateModel(
            name='CreditPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cr_all_sum', models.FloatField()),
                ('cr_first_pay', models.FloatField()),
                ('cr_percent', models.IntegerField()),
                ('cr_period', models.IntegerField()),
                ('cr_month_pay', models.FloatField(null=True)),
                ('cr_percents_sum', models.FloatField(null=True)),
                ('cr_sum_plus_percents', models.FloatField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'credits',
            },
        ),
    ]
