# Generated by Django 4.2 on 2023-04-23 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='acc_name',
            field=models.CharField(default='Счет', max_length=20),
        ),
    ]
